#
# @lc app=leetcode id=389 lang=python3
#
# [389] Find the Difference
#
# https://leetcode.com/problems/find-the-difference/description/
#
# algorithms
# Easy (58.41%)
# Likes:    4289
# Dislikes: 444
# Total Accepted:    556.8K
# Total Submissions: 937.8K
# Testcase Example:  '"abcd"\n"abcde"'
#
# You are given two strings s and t.
# 
# String t is generated by random shuffling string s and then add one more
# letter at a random position.
# 
# Return the letter that was added to t.
# 
# 
# Example 1:
# 
# 
# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
# 
# 
# Example 2:
# 
# 
# Input: s = "", t = "y"
# Output: "y"
# 
# 
# 
# Constraints:
# 
# 
# 0 <= s.length <= 1000
# t.length == s.length + 1
# s and t consist of lowercase English letters.
# 
# 
#

# @lc code=start
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:

        counter_s = Counter(s)
        counter_t = Counter(t)

        for char in counter_t:
            if char not in counter_s:
                return char

            if counter_s[char] != counter_t[char]:
                return char

        return ""
# @lc code=end

